[pytest]
testpaths = tests
pythonpath = .
addopts = -p no:typeguard --basetemp=./.pytest_tmp
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    benchmark: marks benchmark integration tests
