import React from 'react';
import { DataMode } from '../types/mission_control';
import { ShieldAlert, Database, Cpu, XCircle } from 'lucide-react';

interface ModeBadgeProps {
  mode: DataMode;
  tooltip?: string;
  size?: 'sm' | 'md' | 'lg';
}

export const ModeBadge: React.FC<ModeBadgeProps> = ({ mode, tooltip, size = 'md' }) => {
  const configs = {
    CONTROLLED_SYNTHETIC: {
      label: 'CONTROLLED SYNTHETIC',
      desc: 'Generated by controlled hypothesis world. Validates inference & bounded policy behavior.',
      className: 'badge-controlled',
      icon: <ShieldAlert className={size === 'sm' ? 'w-3 h-3' : 'w-3.5 h-3.5'} />,
    },
    HISTORICAL_REPLAY: {
      label: 'HISTORICAL REPLAY',
      desc: 'Uses real historical characterization observations with evaluation oracle strictly firewalled.',
      className: 'badge-replay',
      icon: <Database className={size === 'sm' ? 'w-3 h-3' : 'w-3.5 h-3.5'} />,
    },
    LIVE_COMPUTED: {
      label: 'LIVE COMPUTED',
      desc: 'Computed directly by MultimodalDecisionEngine instance in current session.',
      className: 'badge-live',
      icon: <Cpu className={size === 'sm' ? 'w-3 h-3' : 'w-3.5 h-3.5'} />,
    },
    NOT_AVAILABLE: {
      label: 'NOT AVAILABLE',
      desc: 'Modality linkage absent or external hardware offline. Excluded from valid candidate action space.',
      className: 'badge-unavailable',
      icon: <XCircle className={size === 'sm' ? 'w-3 h-3' : 'w-3.5 h-3.5'} />,
    },
  };

  const current = configs[mode] || configs.CONTROLLED_SYNTHETIC;
  const padding = size === 'sm' ? 'px-2 py-0.5 text-xs' : 'px-2.5 py-1 text-xs';

  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-md font-mono font-medium tracking-wide ${current.className} ${padding}`}
      title={tooltip || current.desc}
    >
      {current.icon}
      <span>{current.label}</span>
    </span>
  );
};
